### ISSUE TITLE
Plugins using this resolver causes `node_modules` to not be removable whilst editor's ESLint is running

### ISSUE THREAD

**Issue by Samuel-Therrien-Beslogic** [unrs/unrs-resolver#159]
If https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint is running on a project with [eslint-plugin-import-x](https://github.com/un-ts/eslint-plugin-import-x) and [eslint-import-resolver-typescript](https://github.com/import-js/eslint-import-resolver-typescript), a lock is established on `node_modules\@unrs\resolver-binding-win32-x64-msvc\resolver.win32-x64-msvc.node`. Making it so any run that needs to remove this file (`npm install` after removing/updating these deps, or having to nuke the `node_modules`) will fail.

The current workaround is to manually disable the ESLint extension + restart the extension host (OR close the editor entirely), then try again.

```
System.UnauthorizedAccessException: Access to the path 'C:\Users\SamuelTherrien\Projects\Beslogic.Libraries\node_modules\@unrs\resolver-binding-win32-x64-msvc\resolver.win32-x64-msvc.node' is denied.
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveFileSystemItem(FileSystemInfo fileSystemInfo, Boolean force)
```

Dprint has a similar issue https://github.com/dprint/dprint-vscode/issues/88 . That issue also mentions a possible workaround. Not sure if it applies here, but since this resolver is called by another plugin, maybe there's something to be done. If not then this is another note to an existing ecosystem-wide issue on Windows (I don't think unix-like systems have that issue).

**Comment by JounQin** [comment]
Sorry I don't quite follow, why `.node` file is locked and by which process? `vscode-eslint` extension or VSCode itself?

**Comment by fredodiable** [comment]
Having a similar problem on Windows after each `npm update` since some months
Adding the command output if it can help

```powershell
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'D:\\Dev\\Web\\media-tracker\\media-tracker-api\\node_modules\\@unrs\\.resolver-binding-win32-x64-msvc-MHmQv4ch',
npm warn cleanup     [Error: EPERM: operation not permitted, unlink 'D:\Dev\Web\media-tracker\media-tracker-api\node_modules\@unrs\.resolver-binding-win32-x64-msvc-MHmQv4ch\resolver.win32-x64-msvc.node'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'unlink',
npm warn cleanup       path: 'D:\\Dev\\Web\\media-tracker\\media-tracker-api\\node_modules\\@unrs\\.resolver-binding-win32-x64-msvc-MHmQv4ch\\resolver.win32-x64-msvc.node'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
```

Fun fact I have 2 differents sub folder in `@unrs` both containing the file `resolver.win32-x64-msvc.node`
- `.resolver-binding-win32-x64-msvc-MHmQv4ch` contains outdated file
- `resolver-binding-win32-x64-msvc` contains the up to date file 

if I close VSCode I can delete the outdated folder which should have been

**Comment by SamuelT-Beslogic** [comment]
Just for reference NX had this issue as well (not always in the context of the eslint extension, but that's where I've hit the issue w/ NX), They supposedly fixed it in v19 (I'm currently upgrading, so we'll see). Here's 3 potentially relevant PRs:
  - 19.0.0 https://github.com/nrwl/nx/pull/22648
  - 19.1.0 https://github.com/nrwl/nx/pull/23375
  - 19.5.0 https://github.com/nrwl/nx/pull/26806

**Comment by JounQin** [comment]
I believe this should be resolved on upstream `napi-rs`'s side, it's a very common issue for all `napi-rs` projects.

Maybe the @nrwl team should contribute their solution into @nap-rs instead, so all `nap-rs` projects will benefit.

**Comment by rjgotten** [comment]
For anyone still having issues:

```diff
diff --git a/node_modules/unrs-resolver/index.js b/node_modules/unrs-resolver/index.js
index 2d0388b..596544e 100644
--- a/node_modules/unrs-resolver/index.js
+++ b/node_modules/unrs-resolver/index.js
@@ -60,6 +60,39 @@ const isMuslFromChildProcess = () => {
   }
 }
 
+// PATCH(unrs-resolver#159): on Windows, load the native binding from a temp copy so that a
+// long-lived process (VS Code's ESLint server) doesn't lock a file inside node_modules.
+function requireWin32FromTempCopy() {
+  if (process.platform !== 'win32' || process.env.NAPI_RS_NATIVE_LIBRARY_PATH || process.env.UNRS_RESOLVER_NO_SHADOWCOPY) {
+    return null
+  }
+  const fs = require('fs')
+  const os = require('os')
+  const path = require('path')
+  const pkg = `@unrs/resolver-binding-win32-${process.arch}-msvc`
+  try {
+    const source = require.resolve(pkg)
+    const version = require(`${pkg}/package.json`).version
+    const dir = path.join(os.tmpdir(), 'unrs-resolver', `${process.arch}-${version}`)
+    const target = path.join(dir, path.basename(source))
+    if (!fs.existsSync(target)) {
+      fs.mkdirSync(dir, { recursive: true })
+      const tmp = `${target}.${process.pid}.tmp`
+      fs.copyFileSync(source, tmp)
+      try {
+        fs.renameSync(tmp, target)
+      } catch {
+        // Another process got there first; its copy is identical
+        try { fs.unlinkSync(tmp) } catch {}
+      }
+    }
+    return require(target)
+  } catch (e) {
+    loadErrors.push(e)
+    return null
+  }
+}
+
 function requireNative() {
   if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
     try {
@@ -523,7 +556,7 @@ function requireNative() {
   }
 }
 
-nativeBinding = requireNative()
+nativeBinding = requireWin32FromTempCopy() || requireNative()
 
 if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
   let wasiBinding = null
```

Aka - a basic shadow-copy, isolated to the Windows platform and using the architecture and version as identity, so the number of shadowcopies doesn't exhibit runaway growth.

Apply with `patch-package` as `unrs-resolver+1.12.2.patch` and pin that version in `package.json` overrides.
Naturally - your responsibility to keep it in-sync. But this works and serves as a decent enough workaround, given that the package author has indicated they have no plans to offer one.

**Comment by JounQin** [comment]
@rjgotten You can raise a PR for napi-rs for long-term solution and benefit the whole napi-rs ecosystem.

**Comment by rjgotten** [comment]
@JounQin 
I would - but this doesn't have proper cleanup inside `%TEMP%`. You still have to occasionally do that yourself, manually.
Lack of any kind of automated collection is why this is nothing more than a workaround. 🙁

Plus- I have my doubts on the longterm robustness of how this locates the `package.json`.
When I wrote 'this works' - I truly meant that in the narrow-band definition.

**Comment by Avasam** [comment]
> I would - but this doesn't have proper cleanup inside %TEMP%. You still have to occasionally do that yourself, manually.

I mean, all OSes have some version of "cleanup temporary files". That's kinda what the temp folder is for. As long as you don't get runaway growth as you said.

The target audience here are devs anyway, not end users. I've had more runaway growth from build systems and package installs. (Looking at you Rust and copy-only node_modules)

In any case, thanks for the patch !
